blank_issues_enabled: true
contact_links:
  - name: Slack Channel
    url: https://pinnacledb.slack.com/
    about: Request a feature, ask a question, or simply say hello

  - name: Docs
    url: https://pinnacledb.github.io/pinnacledb/
    about: Read the docs and
