[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["pinnacledb"]

[project]
name = "pinnacledb"
description = "🔮 Super-power your database with AI 🔮"
readme = "README.md"
license = {file = "LICENSE"}
maintainers = [{name = "Duncan Blythe", email = "opensource@pinnacledb.com"}]
classifiers = [  # TO BE EXTENDED BEFORE RELEASE
    "Development Status :: 1 - Planning",  # TO BE UPDATED BEFORE RELEASE
    "License :: OSI Approved :: Apple Public Source License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Typing :: Typed"  # TO BE CONFIRMED BEFORE RELEASE
]
requires-python = ">=3.8"
dynamic = ["dependencies", "version"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements/requirements.in"] }
version = {attr = "pinnacledb.__version__"}

[project.urls]
homepage = "https://www.pinnacledb.com/"
documentation = "https://www.pinnacledb.com/"  # TO BE UPDATED BEFORE RELEASE
source = "https://www.pinnacledb.com/" # TO BE UPDATED BEFORE RELEASE

[tool.black]
skip-string-normalization = true
target-version = ["py38"]

[tool.mypy]
ignore_missing_imports = true
disable_error_code = [
    "attr-defined",
    "index",
    "union-attr",
    ]

[tool.pytest.ini_options]
addopts = "-W ignore"

[tool.interrogate]
# Uncomment these next lines to generate a badge
#
# badge-format = "svg"
# generate-badge = "docs"

color = true
exclude = []
fail-under = 25.3
ignore-nested-classes = false
ignore-nested-functions = true
ignore-private = true
ignore-property-decorators = true
ignore-regex = []
ignore-semiprivate = true
omit-covered-files = true
quiet = false
verbose = 0
whitelist-regex = []
