[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["pinnacledb"]

[project]
name = "pinnacledb"
version = "0.0.4"  # TO BE UPDATED BEFORE RELEASE
description = "🔮 Super-power your database with AI 🔮"
readme = "README.md"
license = {file = "LICENSE"}
maintainers = [{name = "Duncan Blythe", email = "opensource@pinnacledb.com"}]
classifiers = [  # TO BE EXTENDED BEFORE RELEASE
    "Development Status :: 1 - Planning",  # TO BE UPDATED BEFORE RELEASE
    "License :: OSI Approved :: Apple Public Source License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Typing :: Typed"  # TO BE CONFIRMED BEFORE RELEASE
]
requires-python = ">=3.8"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements/requirements.in"] }

[project.urls]
homepage = "https://www.pinnacledb.com/"
documentation = "https://www.pinnacledb.com/"  # TO BE UPDATED BEFORE RELEASE
source = "https://www.pinnacledb.com/" # TO BE UPDATED BEFORE RELEASE

[tool.black]
skip-string-normalization = true
target-version = ["py38"]

[tool.mypy]
ignore_missing_imports = true
disable_error_code = [
    "call-arg",
    "attr-defined",
    "union-attr",
    "index",
    "misc",
    "assignment"
    ]

[tool.pytest.ini_options]
addopts = "-W ignore"
