[tool.black]
skip-string-normalization = true
target-version = ['py38']

[tool.poetry]
name = "pinnacledb"
version = "0.0.4"
description = "🔮 Super-power your database with AI 🔮"
authors = ["Duncan Blythe <opensource@pinnacledb.com>"]
license = "Apache 2.0"
readme = "README.md"

[tool.poetry.dependencies]
# <4.0 required by upstream dependencies
python = ">=3.8.1, <4.0"
boto3 = ">=1.26.16"
dask = {extras = ["distributed"], version = ">=2022.6.0"}
dill = ">=0.3.6"
fastapi = ">=0.88.0"
fil = ">=1.1.0"
lancedb = ">=0.1.9"  # to be replaced with lance
langchain = ">=0.0.193"
lightning = ">=2.0.4"
networkx = ">=2.8.8"
numpy = ">=1.24.3"
openai = ">=0.27.6"
pillow = ">=9.4.0"
pymongo = ">=4.3.3"
ray = ">=2.4.0"
requests = ">=2.31.0"
scikit-learn = ">=1.1.3"
# TODO: CUDA wheels not currently available on PyPI
torch = ">=2.0.0, !=2.0.1"  # https://github.com/pytorch/pytorch/issues/100974#issuecomment-1544106678  
tqdm = ">=4.64.1"
transformers = ">=4.29.1"
typer = ">=0.7.0"

[tool.poetry.group.dev]
optional = false

[tool.poetry.group.dev.dependencies]
black = ">=23.3.0"
boto3-stubs = ">=1.26.154"
httpx = ">=0.24.1"
impall = ">=1.2.0"
lorem = ">=0.1.1"
mypy = ">=1.3.0"
pytest = ">=7.3.1"
ruff = ">=0.0.267"
tenacity = ">=8.1.0"
types-pillow = ">=9.5.0.4"
types-requests = ">=2.31.0.1"
types-tqdm = ">=4.65.0.1"

[tool.poetry.group.legacy]
optional = false

[tool.poetry.group.legacy.dependencies]
readerwriterlock = ">=1.0.9"
pandas = ">=2.0.2"
flask = ">=2.2.3"
flask-cors = ">=3.0.10"
flask-httpauth = ">=4.7.0"
werkzeug = ">=2.2.3"

[tool.poetry.group.vector-database]
optional = false

[tool.poetry.group.vector-database.dependencies]
faiss-cpu = ">=1.7.4"
pymilvus = ">=2.2.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
