[tool.poetry]
name = "pinnacledb"
version = "0.0.3dev1"
description = "🔮 Super power your database with AI 🔮"
authors = ["Duncan Blythe <opensource@pinnacledb.com>"]
license = "Apache 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
boto3 = "^1.26.134"
dask = {extras = ["distributed"], version = "^2023.5.0"}
dill = "^0.3.6"
faiss-cpu = "^1.7.4"
flask = "^2.3.2"
flask-cors = "^3.0.10"
flask-httpauth = "^4.8.0"
lightning = "^2.0.2"
matplotlib = "^3.7.1"
networkx = "^3.1"
numpy = "^1.24.3"
pillow = "^9.5.0"
pymongo = "^4.3.3"
pytorch-lightning = "^2.0.2"
requests = "^2.30.0"
scikit-learn = "^1.2.2"
sentence-transformers = "^2.2.2"
torch = "^2.0.1"
transformers = "^4.29.1"
tqdm = "^4.65.0"
werkzeug = "^2.3.4"
openai = "^0.27.6"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
coverage = "^7.2.5"
impall = "^1.2.0"
lorem = "^0.1.1"
mypy = "^1.3.0"
pytest = "^7.3.1"
ruff = "^0.0.267"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
