artifact_store: null
bytes_encoding: Bytes
cluster:
  cdc:
    uri: null
  compute:
    uri: null
metadata_store: duckdb:///deploy/testenv/cache/test_duckdb.ddb
data_backend: duckdb://deploy/testenv/cache/test_duckdb.ddb
downloads:
  folder: null
  headers:
    User-Agent: me
  n_workers: 0
  timeout: null
fold_probability: 0.05
lance_home: .pinnacle/vector_indices
log_level: INFO
logging_type: SYSTEM
retries:
  stop_after_attempt: 2
  wait_max: 10.0
  wait_min: 4.0
  wait_multiplier: 1.0
