version: "3.9"
services:

  # PostgreSQL
  # ------------------------------
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pinnacle
      - POSTGRES_PASSWORD=pinnacle
      - POSTGRES_DB=test_db