artifact_store: filesystem:///tmp/artifacts
bytes_encoding: Bytes
cluster:
  compute:
    uri: ray://localhost:10001
  vector_search:
    uri: http://localhost:8000
    backfill_batch_size: 100
  rest:
    uri: http://0.0.0.0:8002
    config: "rest.yaml"
data_backend: mongodb://localhost:27017/documentation
downloads:
  folder: null
  headers:
    User-Agent: me
  n_workers: 0
  timeout: null
fold_probability: 0.05
lance_home: .pinnacle/vector_indices
log_level: INFO
logging_type: SYSTEM
RAY_DEPLOYMENT: 1
metadata_store: null
retries:
  stop_after_attempt: 2
  wait_max: 10.0
  wait_min: 4.0
  wait_multiplier: 1.0
