version: "3.9"
services:

  # Oracle SQL Server
  # ------------------------------
  oracle:
    image: gvenzl/oracle-free
    ports:
      - "1521:1521" # TLS
      - "1522:1522" # mTLS
      - "8443:8443" # HTTPS port for ORDS / APEX and Database Actions
      - "27017:27017" # Mongo API
    environment:
      ORACLE_PASSWORD: admin
      APP_USER: pinnacle
      APP_USER_PASSWORD: pinnacle
      ORACLE_DATABASE: test_db
