# This workflow will install Python dependencies, build docs and commit the changes

name: SuperDuperDB-Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10.6"]

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r docs/requirements.txt
    - name: Build docs
      run: |
        cd docs
        make github
        cd ../
    - name: Commit and Push changes
      run: |
        git add docs/
        git commit -am "Automated docs builder"
        git push
