name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # allows you to trigger manually

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: ["3.8"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'requirements/requirements-dev.txt'
      - name: Install Python packages
        run: pip install -r requirements/requirements-dev.txt
      - name: Cache mypy
        uses: actions/cache@v3
        with:
          path: ./.mypy_cache
          key: mypy|${{ matrix.python-version }}|${{ hashFiles('pyproject.toml') }}
      - name: Run tests
        run: make test
        