name: Documentation
on:
  push:
    branches:
      - main
    paths:  # only run this action when the docs folder is changed
      - 'docs/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache
        with:
          # https://blog.allenai.org/python-caching-in-github-actions-e9452698e98d
          path: |
            ${{ env.pythonLocation }}
          key: 3.10-ubuntu-latest-${{ hashFiles('.github/ci-pinned-requirements/docs.txt') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install -r .github/ci-pinned-requirements/docs.txt
    
      - name: Build docs
        # doc build is available in .cache/docs
        run: |
          python -m pinnacledb docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .cache/docs
          cname: docs.pinnacledb.com
          enable_jekyll: true
