name: Repo Healthcheck

on:
  schedule:
    # Triggers the workflow every day at 0130 UTC
    - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
    #---------------------------------------------------
    # Repo Analytics
    #---------------------------------------------------
    repo-analytics:
      runs-on: ubuntu-22.04
      environment: "analytics"
      steps:
        - uses: jgehrcke/github-repo-stats@HEAD
          with:
            ghtoken: ${{ secrets.GH_TOKEN_ANALYTICS }}

    #---------------------------------------------------
    # Check for broken links in *md files
    #---------------------------------------------------
#    markdown-link-check:
#      runs-on: ubuntu-latest
#      steps:
#      - uses: actions/checkout@master
#      - name: Create configuration for handling relative paths
#        # regex validation: https://regex101.com/r/L2M2wa/1
#        run: |
#          cat <<EOF > mlc_config.json
#          {
#            "replacementPatterns": [
#              {
#              "pattern": "^[./]",
#              "replacement": "{{BASEURL}}/"
#              }
#              ]
#          }
#          EOF
#      - uses: gaurav-nelson/github-action-markdown-link-check@v1
#        with:
#          config-file: 'mlc_config.json'