name: Vulnerability Scanning

on:
  pull_request:
    branches:
      - main
      - '[0-9]+.[0-9]+'
    paths: # Paths that may affect code quality
      - 'pinnacle/**'
      - 'test/**'
      - 'pyproject.toml'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      # Run Trivy to scan the codebase
      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@0.29.0
        with:
          scan-type: "fs"
          scan-ref: .
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          exit-code: 1
          format: sarif
          output: trivy-report.sarif

      - name: Upload Vulnerability Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.sarif
          retention-days: 30
